### PR TITLE
Add code, tests, and data files for LI smart chamber

### PR DESCRIPTION
**Pull request by bpbond**
@wilsonsj100 @robertapeixoto Adding the smart chamber reading code from https://github.com/bpbond/licorsc (which will go away shortly) to the package. Feedback welcome!

### CODE REVIEW

**Comment by bpbond** [comment]
@wilsonsj100 I'll be at SERC tomorrow if useful to discuss in person

**Comment by robertapeixoto** [comment]
@wilsonsj100 I used this code to create a csv from the smart chamber, and it works great! My idea was to use the start time, total volume for each collar, and air temperature from the smart chamber file to create our metadata that can be used/linked in the fluxfinder to calculate the flux and compare the smart chamber (in my case, including manual QAQC) vs. fluxfinder final calculations. I have not yet done it, but I can work more on that tomorrow.

**Comment by wilsonsj100** [comment]
[celebrate]     Wilson, Stephanie reacted to your message:
________________________________

**Comment by bpbond** [comment]
Merging; we can revisit/update as needed. Thanks!

**Comment by wilsonsj100** [comment]
[celebrate]     Wilson, Stephanie reacted to your message:
________________________________

**Pull request merged**
